/**
 * Path helpers and naming utilities for the Feature Engineer extension.
 *
 * Pure functions only — no I/O. The orchestrators read the filesystem and
 * pass the results into prompt builders.
 *
 * Filename convention
 * -------------------
 * Generated files in a project are prefixed with a two-digit number
 * reflecting the order in which they are produced. This makes a plain
 * `ls -1` show the files in generation order without any extra tooling.
 *
 *   per-project (`.feature-engineer/`):
 *     01-actors.md
 *     02-structure.md
 *     03-tech-stack.md
 *     04-qa-static-tools.md
 *     05-qa-engineering.md
 *     06-git-strategy.md
 *
 *   per-feature (`feature-NNN-slug/`):
 *     01-requirement.md
 *     02-relevant-components.md
 *     03-technical-architecture.md
 *     04-technical-plan-testing.md
 *     05-technical-plan-implementation.md
 *     06-review-concerns-to-address.md
 *
 *   project root registry (unprefixed — it's a special file, not a
 *   spec artifact):
 *     features-index.md
 *
 * Templates in `~/.pi/agent/feature-engineer/templates/` are NOT
 * prefixed. The prefix is for the GENERATED artifacts in a project,
 * not the seed templates.
 *
 * The type names (`ConfigFileName`, `ArtifactFileName`) stay
 * unprefixed. The prefix is applied by the path helpers
 * (`configFilePath`, `artifactPath`, etc.) so callers don't have
 * to know the numbers.
 */

import { homedir } from "node:os";
import { join } from "node:path";

/** Name of the directory that holds all Feature Engineer files in a project. */
export const FEATURE_DIR_NAME = ".feature-engineer";

/** Path of the user's pi agent config dir (templates live under this). */
export const PI_AGENT_DIR_NAME = ".pi/agent";

/** Subdirectory under the pi agent dir that hosts feature-engineer state. */
export const GLOBAL_FE_DIR_NAME = "feature-engineer";

/** Name of the features index file maintained by the GitHub skill. */
export const FEATURES_INDEX_FILENAME = "features-index.md";

/** Name of the per-feature directory inside FEATURE_DIR_NAME. */
export const FEATURE_DIR_PREFIX = "feature-";

/** Subdirectory containing user-editable config templates. */
export const CONFIG_TEMPLATES_DIR = "config";

/** Subdirectory containing user-editable per-feature artifact templates. */
export const ARTIFACT_TEMPLATES_DIR = "artifacts";

/** Maximum slug length to keep filenames manageable. */
export const MAX_SLUG_LENGTH = 64;

/** Default width for zero-padded feature IDs. */
export const DEFAULT_ID_WIDTH = 3;

/** All config files written by the Analyse Codebase skill. */
export const CONFIG_FILES = [
  "actors",
  "structure",
  "tech-stack",
  "qa-static-tools",
  "qa-engineering",
  "git-strategy",
] as const;

/**
 * All artifact names referenced in the codebase, in the order they are
 * generated by the skills. The order is reflected in the numeric prefix
 * used in on-disk filenames (see `ARTIFACT_FILE_PREFIX`).
 *
 * `review-concerns` is a TEMPLATE name only (no per-feature file uses
 * this name). The actual per-feature output is `review-concerns-to-address`.
 */
export const ARTIFACT_FILES = [
  "requirement",
  "relevant-components",
  "technical-architecture",
  "technical-plan-testing",
  "technical-plan-implementation",
  "review-concerns-to-address",
  "review-concerns",
] as const;

export type ConfigFileName = (typeof CONFIG_FILES)[number];
export type ArtifactFileName = (typeof ARTIFACT_FILES)[number];

/**
 * Numeric prefix added to per-project config files on disk. The
 * ordering reflects the natural sequence of analysis: actors are
 * the foundation, structure follows, tech stack and QA rules are
 * derived, git strategy is operational.
 */
export const CONFIG_FILE_PREFIX: Record<ConfigFileName, string> = {
  "actors": "01",
  "structure": "02",
  "tech-stack": "03",
  "qa-static-tools": "04",
  "qa-engineering": "05",
  "git-strategy": "06",
};

/**
 * Numeric prefix added to per-feature artifact files on disk. The
 * ordering reflects the order the skills generate them:
 *
 *   1. `requirement`              — req-gathering
 *   2. `relevant-components`     — tech-design phase 1 (intermediate)
 *   3. `technical-architecture`  — tech-design phase 2
 *   4. `technical-plan-testing`  — test-planning
 *   5. `technical-plan-implementation` — impl-planning
 *   6. `review-concerns-to-address` — review-completion (8 passes)
 *
 * `review-concerns` is a template name with no per-feature output,
 * so it has no prefix here.
 */
export const ARTIFACT_FILE_PREFIX: Partial<Record<ArtifactFileName, string>> = {
  "requirement": "01",
  "relevant-components": "02",
  "technical-architecture": "03",
  "technical-plan-testing": "04",
  "technical-plan-implementation": "05",
  "review-concerns-to-address": "06",
};

/**
 * Returns the on-disk filename for a per-project config file, with
 * the numeric prefix (e.g. `"actors"` → `"01-actors.md"`). Exposed
 * for tests and for callers that need the bare filename.
 */
export function configFileDiskName(name: ConfigFileName): string {
  return `${CONFIG_FILE_PREFIX[name]}-${name}.md`;
}

/**
 * Returns the on-disk filename for a per-feature artifact, with
 * the numeric prefix. Returns `null` for names that aren't
 * per-feature outputs (e.g. the `review-concerns` template name).
 */
export function artifactFileDiskName(name: ArtifactFileName): string | null {
  const prefix = ARTIFACT_FILE_PREFIX[name];
  if (prefix === undefined) return null;
  return `${prefix}-${name}.md`;
}

/**
 * Converts a free-form title into a URL- and filename-safe slug.
 *
 * Strategy: lowercase, replace any non-`[a-z0-9]` run with `-`, trim
 * leading/trailing hyphens, drop emoji and most non-ASCII letters.
 *
 * Empty input or input consisting only of separators yields an empty string.
 * Result is truncated to MAX_SLUG_LENGTH characters.
 */
export function toSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, MAX_SLUG_LENGTH)
    .replace(/-+$/g, "");
}

/**
 * Zero-pads a numeric feature ID for directory names.
 *
 * Uses DEFAULT_ID_WIDTH by default; once an ID exceeds 10^width digits,
 * the wider representation is used so `0010` and `10` never collide.
 */
export function padId(id: number, width: number = DEFAULT_ID_WIDTH): string {
  const str = String(id);
  if (str.length >= width) return str;
  return str.padStart(width, "0");
}

/**
 * Parses a directory name of the form `feature-NNN-slug` and returns the
 * numeric ID and slug. Returns null if the name does not match.
 */
export function parseFeatureIdFromDirName(
  dirName: string,
): { id: number; slug: string } | null {
  const match = /^feature-(\d+)-(.+)$/.exec(dirName);
  if (!match || !match[1] || !match[2]) return null;
  const id = Number.parseInt(match[1], 10);
  if (!Number.isFinite(id)) return null;
  return { id, slug: match[2] };
}

/**
 * Determines the next feature ID given a list of directory entries.
 *
 * Non-feature entries (e.g. `templates`, `.DS_Store`, malformed names) are
 * ignored. If no feature directories exist, returns 1.
 */
export function getNextFeatureId(entries: readonly string[]): number {
  let max = 0;
  for (const entry of entries) {
    const parsed = parseFeatureIdFromDirName(entry);
    if (parsed && parsed.id > max) max = parsed.id;
  }
  return max + 1;
}

/** Absolute path to the `.feature-engineer/` directory for a project. */
export function featureEngineerDir(cwd: string): string {
  return join(cwd, FEATURE_DIR_NAME);
}

/** Absolute path to the per-feature directory. */
export function featureDirPath(cwd: string, id: number, slug: string): string {
  return join(featureEngineerDir(cwd), `${FEATURE_DIR_PREFIX}${padId(id)}-${slug}`);
}

/**
 * Absolute path to the features-index.md file. Unprefixed — it's a
 * project-wide registry, not a per-feature artifact.
 */
export function featureIndexPath(cwd: string): string {
  return join(featureEngineerDir(cwd), FEATURES_INDEX_FILENAME);
}

/**
 * Absolute path to the user's global Feature Engineer directory.
 * Templates live here (under `templates/`) so a user customises them once
 * and every project uses the same set.
 *
 * @param homeDir override for tests; defaults to `os.homedir()`
 */
export function globalFeatureEngineerDir(homeDir: string = homedir()): string {
  return join(homeDir, PI_AGENT_DIR_NAME, GLOBAL_FE_DIR_NAME);
}

/** Absolute path to the user's global templates directory. */
export function globalTemplatesDir(homeDir: string = homedir()): string {
  return join(globalFeatureEngineerDir(homeDir), "templates");
}

/**
 * Absolute path to a config template file under the user's *global* templates
 * directory. Templates are seeded once into `~/.pi/agent/feature-engineer/`
 * and shared across all of the user's projects. Note: templates are NOT
 * prefixed with the numeric ordering — the prefix is for the GENERATED
 * files in a project, not the seed templates.
 *
 * @param homeDir override for tests; defaults to `os.homedir()`
 */
export function configTemplatePath(
  name: ConfigFileName,
  homeDir: string = homedir(),
): string {
  return join(globalTemplatesDir(homeDir), CONFIG_TEMPLATES_DIR, `${name}.md`);
}

/**
 * Absolute path to a config file written by the Analyse Codebase skill.
 * The on-disk filename includes the numeric prefix (e.g. `01-actors.md`).
 */
export function configFilePath(cwd: string, name: ConfigFileName): string {
  return join(featureEngineerDir(cwd), configFileDiskName(name));
}

/**
 * Absolute path to an artifact template file under the user's *global*
 * templates directory. See {@link configTemplatePath}. Note: templates
 * are NOT prefixed.
 *
 * @param homeDir override for tests; defaults to `os.homedir()`
 */
export function artifactTemplatePath(
  name: ArtifactFileName,
  homeDir: string = homedir(),
): string {
  return join(globalTemplatesDir(homeDir), ARTIFACT_TEMPLATES_DIR, `${name}.md`);
}

/**
 * Absolute path to an artifact file written inside a feature directory.
 * The on-disk filename is prefixed with its numeric order (e.g.
 * `requirement` → `01-requirement.md`). For names that aren't
 * per-feature outputs (e.g. the `review-concerns` template name),
 * throws — callers should use `artifactTemplatePath` for those
 * instead.
 */
export function artifactPath(
  cwd: string,
  id: number,
  slug: string,
  name: ArtifactFileName,
): string {
  const filename = artifactFileDiskName(name);
  if (filename === null) {
    throw new Error(
      `artifactPath: "${name}" is a template name, not a per-feature output. Use artifactTemplatePath() instead.`,
    );
  }
  return join(featureDirPath(cwd, id, slug), filename);
}

/**
 * Absolute path to the intermediate `02-relevant-components.md` file
 * written by the tech-design skill (phase 1). Always prefixed.
 */
export function relevantComponentsPath(
  cwd: string,
  id: number,
  slug: string,
): string {
  return join(featureDirPath(cwd, id, slug), artifactFileDiskName("relevant-components")!);
}

/**
 * Absolute path to the `06-review-concerns-to-address.md` file
 * written by the review-completion skill. Always prefixed.
 */
export function reviewConcernsPath(
  cwd: string,
  id: number,
  slug: string,
): string {
  return join(featureDirPath(cwd, id, slug), artifactFileDiskName("review-concerns-to-address")!);
}
